#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config \
    /dev/input/mice

# clean up old PIDs
rm -rf "/config/BOINC Manager-abc"

if [[ ! -n "$PASSWORD" ]]; then
    echo "**** No auth enabled. To enable auth, you can set the PASSWORD var in docker arguments. ****"
fi

# permissions
chown -R abc:abc \
    /config
