#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config \
	/dev/input/mice

# clean up old PIDs
rm -rf "/config/BOINC Manager-abc"

# handle password access
sed -i 's|"password":"abc",|"password":"kjhbouygiuvhgvghv",|' /gclient/app.js
if ([ -n "$GUAC_USER" ] || [ -n "$GUAC_PASS" ]) && [ -z "$PASSWORD" ]; then
	echo '
********************************************************
********************************************************
****                                                ****
****  GUAC_USER and GUAC_PASS vars are deprecated   ****
****                                                ****
****  Temporary credentials are being set:          ****
****                                                ****
****  User: abc                                     ****
****  Pass: abc                                     ****
****                                                ****
****                                                ****
****  See the readme for new credential info        ****
****                                                ****
****                                                ****
********************************************************
********************************************************'
elif [ -n "$PASSWORD" ]; then
	echo "abc:${PASSWORD}" | chpasswd
	echo "Setting password from environment variable."
else 
	echo "abc:kjhbouygiuvhgvghv" | chpasswd
	echo "No password is set for the interface."
fi

# permissions
chown -R abc:abc \
	/config
